title: Étienne Després
author: Étienne Després
description: "Design, vidéo, 3D, plein d’affaires."
permalink: /:title
host: 127.0.0.1
exclude:
  - CNAME
  - Gemfile
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - Rakefile
  - README.md
  - webpack.config.js
  - yarn.lock

collections:
  projects-en:
    output: true
    permalink: /en/projects/:title
  projects-fr:
    output: true
    permalink: /projets/:title

defaults:
  -
    scope:
      path: ""
      type: "projects-en"
    values:
      thumbnail-format: "jpg"
  -
    scope:
      path: ""
      type: "projects-fr"
    values:
      thumbnail-format: "jpg"
      
i18n:
  fr:
    description: "Design, vidéo, 3D, plein d’affaires."
    coolness: "Niveau de coolness non-garanti."
    all_projects: 'Tous les projets'
    next_project: 'Projet suivant'
    index_url: '/'
    index_link: 'Page d’accueil Étienne Després'
    projects: "Projets"
    video: "Vidéo &amp; 3D"
    design: "Design"
    about: "À propos"
    contact: "Contact"
    language: "English"
    preview: "Aperçu"
  en:
    description: 'Design, video, 3D, all kinds of stuff.'
    coolness: "Coolness level not guaranteed."
    all_projects: 'All projects'
    next_project: 'Next project'
    index_url: '/en/'
    index_link: 'Étienne Després Home Page'
    projects: "Projects"
    video: "Video &amp; 3D"
    design: "Design"
    about: "About"
    contact: "Contact"
    language: "Français"
    preview: "Preview image"
    