title: Étienne Després
author: Étienne Després
description: "Design, vidéo, 3D, plein d’affaires."
permalink: /:title
host: 0.0.0.0
exclude: ['node_modules', 'yarn.lock', 'webpack.config.js', 'package.json']

collections:
  projects-en:
    output: true
    permalink: /en/projects/:title
  projects-fr:
    output: true
    permalink: /projets/:title

types: [video, design]

defaults:
  -
    scope:
      path: ""
      type: "projects-en"
    values:
      thumbnail-format: "jpg"
  -
    scope:
      path: ""
      type: "projects-fr"
    values:
      thumbnail-format: "jpg"
      
i18n:
  fr:
    description: "Design, vidéo, 3D, plein d’affaires."
    all_projects: 'Tous les projets'
    next_project: 'Projet suivant'
    index_url: '/'
    index_link: 'Page d’accueil Étienne Després'
    video: "Vidéo &amp; 3D"
    design: "Design"
    about: "À propos"
    contact: "Contact"
    language: "English"
    preview: "Aperçu"
  en:
    description: 'Design, video, 3D, all kinds of stuff.'
    all_projects: 'All projects'
    next_project: 'Next project'
    index_url: '/en/'
    index_link: 'Étienne Després Home Page'
    video: "Video &amp; 3D"
    design: "Design"
    about: "About"
    contact: "Contact"
    language: "Français"
    preview: "Preview image"
    