title: Étienne Després
author: Étienne Després
description: "Design, programmation, 3D, illustration et autres patentes."
permalink: /:title
host: 0.0.0.0

collections:
  projects-en:
    output: true
    permalink: /en/projects/:title
  projects-fr:
    output: true
    permalink: /projets/:title

types: [video, design]

i18n:
  fr:
    video: "Vidéo & 3D"
    design: "Design"
    contact: "Contact"
    language: "English"
  en:
    video: "Video & 3D"
    design: "Design"
    contact: "Contact"
    language: "Français"
    